### ISSUE TITLE
Expecting Client to find and Connect to Authenticator

### ISSUE THREAD

**Issue by pzboyz** [jovasco/u2f-ref-code#11]
When trying to run BLECertfication tool we find in many test cases the tool will not find and connect to our device.

On closer inspection if we run the tool using a SecureClick there is a connection. With a BLE sniffer we can see that SecureClick is sending CONNECT_IND messages to force the connection to the PC. This behaviour is allowed, but it is not the only allowed behaviour.

Our devices, and I expect many devices, sit sending undirected ADV_ID packets which can be seen, but are not detected/filtered by the tool. So we are stuck at the start of the function U2FTests() in WaitForUserPrescence().

How do we change the BLECertificationTool code to get the connection initiated by the PC?

**Comment by jovasco** [comment]
First, where does the tool hang? Is it in WaitForDevice()?

The tool does not wait for any specific advertisement type, so any advertisement that makes it through the Windows stack should work. If it sees one, it tries to read a characteristic to trigger a connection. Windows does not allow for anything else, so this is already best effort.

I am unsure why you see connection initiation from the SecureClick but this is not something we have explicitly implemented, although I guess it is possible this is just how Nordic implemented their stack. Can you provide a full trace?

**Comment by jovasco** [comment]
To know if your advertisement makes it through the Windows stack, put a break point in BleDeviceWinRT::OnAdvertisementReceived().

**Comment by jovasco** [comment]
When running the tool, I see windows sending a CONNECT_REQ to the SecureClick, so it is Windows that initiates the connection?

![capture](https://cloud.githubusercontent.com/assets/11663275/26575461/a2f664fe-4525-11e7-9abc-f579872d73e9.PNG)

**Comment by pzboyz** [comment]
Yeah I agree, I did look at this again quickly last week too and started to think that it might be my sniffer which is hiding some information from me, I believe you and I need to raise an issue with the maker of my sniffer. So we can close this.
