### ISSUE TITLE
#Feature Showing Exchanged APDUs on Command Line

### ISSUE THREAD

**Issue by denizea** [jovasco/u2f-ref-code#2]
Hi Johan,

Does your testing tool support showing exchanged APDUs on command line? If so, can you please tell me what is the input parameter for that? If not, I think it would be nice feature that how tool receive / transmit data. 

What do you think about it?

**Comment by jovasco** [comment]
No, it does not support this at this time. I will add it.

**Comment by jovasco** [comment]
I have added a -T option to trace the low level BLE reads and writes.

**Comment by denizea** [comment]
Thank you Johan! This really helps.
