### ISSUE TITLE
mincrypt library has been removed from Android's platfor/system/core repo

### ISSUE THREAD

**Issue by david-at-nymi** [jovasco/u2f-ref-code#3]
The change has been made recently in the following commit
https://android.googlesource.com/platform/system/core/+/6b11c13aed5934ea38f0747324006491c8daecdd
Commit prior to this one seem to be fine

**Comment by jovasco** [comment]
I will adjust the path in the build instructions to
https://android.googlesource.com/platform/system/core/+/lollipop-release/
which still contains mincrypt.
