### ISSUE TITLE
std::to_string in MSVC

### ISSUE THREAD

**Issue by chriswifx** [jovasco/u2f-ref-code#4]
std::to_string with an int parameter can't resolve in pre November 2012 versions of MSVC

cast parameter to (long long) works
- Chris

**Comment by jovasco** [comment]
I have added the cast for MSVC version 2010 or earlier
I have clarified the building instructions to use MSVC2010 or higher.

**Comment by jovasco** [comment]
If you can confirm this works, I can close this issue, thanks.

**Comment by chriswifx** [comment]
Works fine on Win 10
