### ISSUE TITLE
Multiple Command Fragment test

### ISSUE THREAD

**Issue by chriswifx** [jovasco/u2f-ref-code#7]
I’d like to discuss test 3#.

If we have , for example a Control Point length of 512 bytes , this test says that I must deal with command messages longer than 512 bytes, which is already several times longer than any reasonable command message.

I’d like to question the value of testing with command sequences > 512 bytes

Would we be better off 
- Agreeing a minimum command  message length that the token must be able to deal with
  and/or 
- Allowing the token to immediately inspect the u2F message data and immediately reject commands in which the u2f message is ill-formed?

Best – Chris

**Comment by jovasco** [comment]
As discussed elsewhere, if you cannot deal with commands of more than X bytes, you need to answer with a transport layer length error.
